name: Export Clash Meta

on:
  workflow_dispatch:
  push:
    paths:
      - work/nodes.filtered.json
      - export_clash.js

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Export main.yaml
        run: node export_clash.js

      - name: Commit Clash config
        uses: EndBug/add-and-commit@v9
        with:
          message: "export: Clash Meta main.yaml"
          add: work/main.yaml
